form_data_empty = {
    "added_by_name": "",
    "added_by_email": "",
    "software_name": "",
    "official_website": "",
    "license": "",
    "price": "",
    "latest_version": "",
    "date_of_latest_version": "",
    "principal_contact_name": "",
    "principal_contact_email": "",
    "description": "",
    "long_description": "",
    "required_citation": "",
    "languages": "",
    "compilers": "",
    "source_code_link": "",
    "executables": "",
    "code_management": "",
    "continuous_integration": "",
    "number_of_tests": "",
    "test_coverage": "",
    "parallel": "",
    "gpu": "",
    "knl_optimized": "",
    "support_line": "",
    "documentation": "",
    "number_of_tutorials": "",
    "wiki": "",
    "forum": "",
    "mail_list": "",
    "domain": "",
    "mm_features-free_energy_methods": "",
    "mm_features-advanced_sampling_methods": "",
    "mm_features-forcefields": "",
    "mm_features-file_formats": "",
    "mm_features-tags": "",
    "qm_features-basis": "",
    "qm_features-element_coverage": "",
    "qm_features-other": "",
    "qm_features-tags": "",
    "comments": "",
}

form_data_full = {
    "added_by_name": "Doaa Altarawy",
    "added_by_email": "daltarawy@vt.edu",
    "is_SW_owner": "y",
    "software_name": "DeTangle",
    "official_website": "http://www.molssi.org",
    "license": "VA",
    "price": "free",
    "latest_version": "123",
    "date_of_latest_version": "2018-08-14 15:56:00",
    "principal_contact_name": "doaa",
    "principal_contact_email": "doaa.altarawy@gmail.com",
    "description": "<p>More details <strong>here </strong><i><strong>and there</strong></i></p>",
    "long_description": "<p>Long text with format</p>",
    "required_citation": "<p>Also this citation is formatted</p>",
    "languages": ["C++", "Python"],
    "compilers": "GC",
    "gui": "y",
    "source_code_link": "http://www.molssi.org",
    "executables": "no",
    "code_management": "git/GitHub",
    "continuous_integration": "Yes",
    "number_of_tests": "1000",
    "test_coverage": "80",
    "parallel": "Yes",
    "gpu": "Yes",
    "knl_optimized": "Yes",
    "support_line": "http://www.molssi.org",
    "documentation": "http://www.molssi.org",
    "number_of_tutorials": "5",
    "wiki": "http://www.molssi.org",
    "forum": "http://www.molssi.org",
    "mail_list": "http://www.molssi.org",
    "domain": "MM",
    "mm_features-ensembles": ["NPH", "NPT", "NVE"],
    "mm_features-free_energy_methods": "Yes",
    "mm_features-advanced_sampling_methods": "No",
    "mm_features-forcefields": "AMBER",
    "mm_features-file_formats": "text, csv",
    "mm_features-qm_mm": "y",
    "mm_features-tags": ["periodicity_0d", "periodicity_1_and_2d", "periodicity_3d"],
    "qm_features-basis": "Gaussian",
    "qm_features-element_coverage": "all",
    "qm_features-other": "other",
    "qm_features-tags": ["dft", "dft_u"],
    "comments": "More comments here",
}